# Generated by Django 5.1.3 on 2025-03-13 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('synopsis', models.CharField(max_length=1000)),
                ('poster', models.ImageField(default='default_poster.jpg', upload_to='images/posters/')),
                ('genre', models.CharField(choices=[('crime', 'Crime'), ('drama', 'Drama'), ('science fiction', 'Science Fiction')], max_length=50)),
                ('duration', models.IntegerField(verbose_name='duration in minutes')),
                ('director', models.CharField(max_length=255)),
                ('cast', models.CharField(max_length=2500)),
                ('trailer_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorium', models.IntegerField()),
                ('row', models.CharField(max_length=1)),
                ('column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditorium', models.IntegerField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('capacity', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('A', 'Available'), ('F', 'Full'), ('E', 'Expired')], max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('seats', models.ManyToManyField(blank=True, related_name='reservations', to='api.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.showtime')),
            ],
        ),
    ]
