# Generated by Django 5.1.3 on 2024-11-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='reservations',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.seat'),
        ),
    ]
