# Generated by Django 5.1.3 on 2025-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.CharField(default='00000000000', editable=False, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
