# Generated by Django 5.1.3 on 2025-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='valid', max_length=9),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='capacity',
            field=models.IntegerField(default=48),
        ),
    ]
