# Generated by Django 5.1.3 on 2024-11-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_seat_reservations_reservation_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('F', 'Full'), ('E', 'Expired')], max_length=10),
        ),
    ]
