# Generated by Django 5.1.3 on 2024-12-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_showtime_capacity_alter_showtime_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default_poster.jpg', upload_to='images/posters/'),
        ),
    ]
