# Generated by Django 5.1.3 on 2025-02-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.CharField(default='Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum, veniam quis odio maxime minus similique aperiam aliquid voluptatibus ratione esse molestias impedit cupiditate iure, possimus, id at in ea quasi deleniti officiis dolorum. Possimus molestias, expedita numquam nesciunt necessitatibus, dicta corporis eius doloribus minus dolor harum quod. Amet eum, modi provident fugiat fuga, quasi alias adipisci sequi necessitatibus ratione aut illo. Excepturi distinctio placeat dicta libero non? Dolores cum officiis alias velit debitis aliquid, illo eum labore molestias inventore necessitatibus repellat ducimus et pariatur quidem! Molestias unde quidem, similique odit eaque enim sapiente, amet ipsum sit iste ut dolorum exercitationem delectus dignissimos laborum quo natus, eveniet fugit sunt. Incidunt hic laudantium sapiente accusamus quidem temporibus, officia, nulla nemo asperiores vero optio, pariatur obcaecati aliquam odit ex! Nihil quasi eos, dignissimos illo voluptate laboriosam quia necessitatibus veniam sunt provident, molestias nisi deserunt, natus libero incidunt sapiente repellendus ipsam. Laudantium, consequuntur velit. Culpa ratione temporibus delectus praesentium repellat nulla ea deserunt, mollitia natus accusamus laudantium asperiores sunt magnam, quod alias, dolores repudiandae hic unde. Nihil incidunt quidem porro non sunt excepturi nobis molestiae nemo quas numquam optio accusantium voluptate, consectetur corrupti minima provident, tempora modi explicabo repellendus. Aliquid omnis consectetur est natus quae modi ipsam quidem magni tenetur, dolore iusto molestias pariatur, excepturi beatae sed alias odit autem dicta eum corrupti porro, animi ipsum. Autem doloribus est libero sit nesciunt ex tempora! Vero inventore repellat recusandae consectetur debitis. Sed, modi itaque neque, quam non molestiae corporis reiciendis, sunt minima fuga maxime accusantium vitae provident voluptatibus dolor! Provident fuga laudantium at. Fugit perspiciatis exercitationem tenetur corrupti consectetur magni cupiditate officiis quos vel rerum saepe optio modi error, alias eveniet suscipit, distinctio libero ad qui. Facere, eos odit doloribus, ducimus facilis, veniam tempora vero omnis dicta tenetur necessitatibus soluta fugiat unde quisquam? Quae, nihil?', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('crime', 'Crime'), ('drama', 'Drama'), ('science fiction', 'Science Fiction')], max_length=50),
        ),
    ]
