# Generated by Django 5.1.3 on 2025-08-29 02:28

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_genre_remove_movie_genre_alter_showtime_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('animation', 'Animation'), ('comedy', 'Comedy'), ('crime', 'Crime'), ('documentary', 'Documentary'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('romance', 'Romance'), ('science fiction', 'Science Fiction'), ('thriller', 'Thriller')], max_length=105),
        ),
    ]
