# Generated by Django 5.1.3 on 2025-03-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_movie_synopsis_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='api.seat'),
        ),
    ]
