### 1. Index / Get all movies:
GET http://localhost:8000/api/movies

### 2. User selects a movie / Get movie details:
GET http://localhost:8000/api/movie/1

### 3. User selects a showtime / Get showtime seats:
GET http://localhost:8000/api/showtime/35

### 4. User selects the seats to reserve / Execute a reservation:
POST http://localhost:8000/api/reserve/
content-type: application/json

{
    "showtime": 41,
    "seats": [304, 305, 306]
}



### List reservations
GET http://localhost:8000/api/reservations
