### 1. Get Token
POST http://localhost:8000/api/auth/token/
content-type: application/json

{
    "username": "admin", "password": "12345"
}

### 2. Get movies
GET http://localhost:8000/api/movies/

### 3. Get auditorium showtimes
GET http://localhost:8000/api/admin/create-showtime/1/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMDE5NTI5LCJpYXQiOjE3NDMwMTc3MjksImp0aSI6IjAxNGI4NTFjNDM0NDRmMGU4NWRkNGNlMmNmM2NiMDBiIiwidXNlcl9pZCI6MX0.q0av_jmkygZj_x2noLtqrM7p2cr6Opnro_nRZpHyOCA

### 4. Create showtime
POST http://localhost:8000/api/admin/create-showtime/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMDE5NTI5LCJpYXQiOjE3NDMwMTc3MjksImp0aSI6IjAxNGI4NTFjNDM0NDRmMGU4NWRkNGNlMmNmM2NiMDBiIiwidXNlcl9pZCI6MX0.q0av_jmkygZj_x2noLtqrM7p2cr6Opnro_nRZpHyOCA

{
    "movie": ...,
    "auditorium": ...,
    "start":...,
}